### ISSUE TITLE
Feature req: Normalised edit distance

### ISSUE THREAD

**Issue by ComedyTomedy** [mjfisheruk/funiq#4]
Short strings don't compare well; e.g. the following outputs a single underscore:

    echo -e '_\n_foo\n_moo' | funiq

Could I request a new flag for normalising the edit distance (i.e. for Levenshtein, dividing it by the length of the longest of the 2 lines)? Perhaps something like:

    -D <float>,  --normalised-distance <float>
    normalise edit distance (overrides -d)

assuming `-d 3` remains the default, it doesn't need a default, but might have a suggested value (which I guess would be low, say 0.05 (= 3/60))

**Comment by mjfisheruk** [comment]
Hi @ComedyTomedy - I apologize for not getting back to you. It's been a while since I've been on GitHub, and I appear to have either not received or missed the notification for your issue.

You're absolutely right about the short strings not comparing well. and I've implemented normalized edit distances in other projects for the same reasons. It would certainly be a useful addition. Current obstacles:

* No tests. Entirely my fault - I did not include tests with this project when I initially created it. I wasn't actually expecting any community engagement, but each time someone has discussed a feature with me I've kicked myself for not starting it right. That means it's hard to verify existing behavior still works with additional changes
* Somewhat organic approach to adding feature flags has led to a set of flags that are becoming a bit inconsistent; that probably needs a bit of thought, or at least proper versioning so I can release some breaking changes with a clear conscience.

Do you still have a need for this (over a year later..)? If people are finding this useful I'm happy to put the work in.

**Comment by ComedyTomedy** [comment]
It's still in a pipeline I use regularly, so if the fix is quick, I would appreciate it :) but also if you're sick of CPP and want to do something else with your hours that's cool too!

**Comment by mjfisheruk** [comment]
> It's still in a pipeline I use regularly, so if the fix is quick, I would appreciate it

I'm really happy someone is getting some use out of it :)

I suspect it can't involve a huge amount of work, but it's been a while since my head has been in this code. Leave it with me for a few days, and I'll see where I get to!

**Comment by mjfisheruk** [comment]
Hi @ComedyTomedy - I've added normalized Levenshtein comparison in PR #6 (as yet un-merged).

You can now specify the comparison method with an extra flag, and the -d parameter is interpreted accordingly, e.g.

```
echo -e '_\n_foo\n_moo' | funiq -d 0.3 -m normalized-levenshtein
```

I realise this is a bit more verbose than your original suggestion, but:

* I didn't want to break existing behaviour by changing any defaults
* Having both `-d` and `-D` flags could be potentially confusing, and requires deciding what to do if someone specifies both at once
* This way gives us an extensible route to adding additional comparison methods should they be required

I'm going to leave that PR to sit for a day or two before I merge it in case anything else occurs to me in the meantime; please do feel free to leave any feedback here or on the PR itself.

Finally, from one Brit to another - I'm sorry about the American English spelling of 'normalize', but it's the world we live in :grin:

**Comment by ComedyTomedy** [comment]
Ah amazing! that seems like a good choice of flags / API :)  definitely better than my suggestion

As an etymology nerd, I secretly approve of most of Webster's American English spelling reforms , but don't tell anyone ;)

A few tools accept both forms of -i[sz]e , but it's not really worth jumping through hoops for!

Thanks ever so much, you're a star ♥️🌟 I'll give it a whirl soon!

**Comment by mjfisheruk** [comment]
> As an etymology nerd, I secretly approve of most of Webster's American English spelling reforms , but don't tell anyone ;)

I shan't tell a soul. As long as it doesn't make it out onto the open internet somehow, your secret is safe :smiley: 

I've added a few notes to the PR to myself to follow up later, but nothing that I anticipate will meaningfully change the functionality, so if you want to start using the build from the branch it should be safe to do so.

> Thanks ever so much, you're a star

No problem; thanks for the original suggestion, and for getting back to me after such a long time. It finally spurred me to add some basic tests, so I feel much more comfortable in my ability to maintain it in the future. Everyone wins!

**Comment by mjfisheruk** [comment]
Morning @ComedyTomedy - #6 is now merged to master. I hope that does the job for you!

I'm provisionally closing this issue to keep things neat - but please do feel free to comment here further, and if there's anything else that occurs to you we can either reopen or create a new issue.

Thanks again for the suggestion, and for taking the time to reach out to me.

**Comment by ComedyTomedy** [comment]
Just realised I never said thank you! Works wonderfully, hope you're well.

**Comment by mjfisheruk** [comment]
No problem at all - glad you're getting some use out of it! Hope you're well too, and surviving lockdown OK :smile:
